### ISSUE TITLE
How to we use  libcrypto.so.1.0.0" is 32-bit instead of 64-bit"

### ISSUE THREAD

**Issue by kamakshi417** [WuglyakBolgoink/cordova-plugin-iroot#10]
Hi Team,

in my project i'm using cordova-plugin-jsonstore and cordova-plugin-iroot. if i use iroot plugin i'm getting error like 
C_DOCUMENT", col: "userDetails", usr: "jsonstore", …}
col: "userDetails"
doc: "dlopen failed: "/data/data/packagename/no_backup/libcrypto.so.1.0.0" is 32-bit instead of 64-bit"
err: -11
msg: "OPERATION_FAILED_ON_SPECIFIC_DOCUMENT"
res: {}
src: "initCollection"
usr: "jsonstore"

Please let us know is there way to compile   32-bit libcrypto.so. instead of 64-bit.

Thanks,
Kamakshi

**Comment by WuglyakBolgoink** [comment]
Hallo @kamakshi417 any news?

**Comment by Maheshbhusanoor** [comment]
**Add below lines of code into build.gradle**


```
defaultConfig { // inside of defaulConfig

//Add ndk

 ndk {
     abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
   }
}
```

**Comment by WuglyakBolgoink** [comment]
@Maheshbhusanoor thank you for information!
