### ISSUE TITLE
Limit jniLibs to only armeabi-v7a

### ISSUE THREAD

**Issue by juan9506** [WuglyakBolgoink/cordova-plugin-iroot#13]
Hi, I have one app that have compatibility with all devices, but only when there's no native libraries but armeabi-v7a, after adding this plugin, it creates several other architectures libtool-checker.so files (mips, mips64, x86_64 ...) and this is making my app crash.
Do you know how to limit the plugin so the only generated native library is for armeabi-v7a?
I've been looking through all the code and didn't found where it defines these architectures.
Thanks.

**Comment by WuglyakBolgoink** [comment]
@juan9506 This plugin is a wrapper to https://github.com/scottyab/rootbeer library. Please ask same in this repo and link our ticket too.

**Comment by juan9506** [comment]
I solved this by using the following plugin: https://github.com/Jween/android-soexcluder
what it does is removing and including only the desired .so files, so in my case, I only included the armeabi-v7a .so file and removed all the others.
