### ISSUE TITLE
Build is getting failed after installing the plugin.Any updates in it?

### ISSUE THREAD

**Issue by Maheshbhusanoor** [WuglyakBolgoink/cordova-plugin-iroot#14]
Trying to build but i am getting error following error

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.scottyab:rootbeer:0.0.6.
  Required by:
      project :app
   > Could not resolve com.github.scottyab:rootbeer:0.0.6.
      > Could not get resource 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.6/rootbeer-0.0.6.pom'.
         > Could not GET 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.6/rootbeer-0.0.6.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
14 actionable tasks: 14 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.scottyab:rootbeer:0.0.6.
  Required by:
      project :app
   > Could not resolve com.github.scottyab:rootbeer:0.0.6.
      > Could not get resource 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.6/rootbeer-0.0.6.pom'.
         > Could not GET 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.6/rootbeer-0.0.6.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by WuglyakBolgoink** [comment]
Hallo @Maheshbhusanoor Did you try to check it with latest version?

**Comment by smnel83** [comment]
Hi, I'm also getting the same error, although for against version 0.0.7

Could not resolve com.github.scottyab:rootbeer:0.0.7.
> Could not get resource 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.7/rootbeer-0.0.7.pom'.
> Could not GET 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.7/rootbeer-0.0.7.pom'.

@Maheshbhusanoor have you managed to find a solution or still getting build error?

**Comment by WuglyakBolgoink** [comment]
Hallo @smnel83 / @Maheshbhusanoor 

Do you have access to https://jitpack.io/? try to check if u can load it:
![image](https://user-images.githubusercontent.com/2271337/51732145-9daef300-207d-11e9-89ca-f9af6477ee7b.png)

1) I created a fresh new project, added Android and iRoot plugin. Build android project - there are NO errors in build process.
2) And I can open a link 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.7/rootbeer-0.0.7.pom':
![image](https://user-images.githubusercontent.com/2271337/51732174-b0292c80-207d-11e9-91a5-1a2b1505bb5b.png)


Please check with new cordova project too.

**Comment by smnel83** [comment]
@WuglyakBolgoink Thanks, I'll give a new cordova project a try, although I can get to both links ok, the build process for some strange reason fails. 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not resolve com.github.scottyab:rootbeer:0.0.7.
     Required by:
         project :
      > Could not resolve com.github.scottyab:rootbeer:0.0.7.
         > Could not get resource 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.7/rootbeer-0.0.7.pom'.
            > Could not GET 'https://jitpack.io/com/github/scottyab/rootbeer/0.0.7/rootbeer-0.0.7.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Maheshbhusanoor** [comment]
I have did some changes to get it done. androidMinSdkversion upgrade to 19 n above and install plugin version 0.3.0

**Comment by WuglyakBolgoink** [comment]
@smnel83 I think your error was described in this issue: https://github.com/gradle/gradle/issues/4170

**Comment by WuglyakBolgoink** [comment]
Closing this for now, feel free to reopen.
