### ISSUE TITLE
Throwing false positives on some android devices

### ISSUE THREAD

**Issue by jdmartins** [WuglyakBolgoink/cordova-plugin-iroot#16]
I'm experiencing some false positives on  **android** 

I'm using the `isRooted` method with **BUSYBOX** disabled

```
<plugin name="cordova-plugin-iroot" spec="0.8.0">
  <variable name="ENABLE_BUSYBOX_CHECK" value="false" />
</plugin>
```
List of affected devices so far:
* Samsung Galaxy A8 @ _probably_ **Android 6**
* Lenovo TAB 4 10 @ **Android 7.1**

Do you have any ideas why this might be happening or how to solve it?

Cheers

**Comment by WuglyakBolgoink** [comment]
Hallo @jdmartins With this problem it will be better to create an issue directly hier: https://github.com/scottyab/rootbeer/issues

**Comment by jdmartins** [comment]
Thanks, I will close it then
