### ISSUE TITLE
requireCordovaModule issue with cordova 9

### ISSUE THREAD

**Issue by JoaoVFAraujo** [WuglyakBolgoink/cordova-plugin-iroot#20]
After upgrading Cordova to version 9 I get this error message:

> Failed to install 'cordova-plugin-iroot': CordovaError: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

 Is there a way, how to fix this?

**Comment by dmastag** [comment]
@WuglyakBolgoink i see that the pull request https://github.com/WuglyakBolgoink/cordova-plugin-iroot/pull/19 has been merged which should have fixed this.

Would it be possible to release that?

**Comment by WuglyakBolgoink** [comment]
Hallo @dmastag sorry, I haven't time for this last weeks, I try to up this week!

**Comment by nationdata-it** [comment]
Hi @WuglyakBolgoink 

any update on this?

**Comment by WuglyakBolgoink** [comment]
Hallo guys! sorry.. didn't have any time for us ^_^

I do update on this weekend!

**Comment by davidzxc12** [comment]
Hi @WuglyakBolgoink 

Is there any update on this issue?

thanks.

**Comment by nationdata-it** [comment]
Hi @WuglyakBolgoink 

Any update on this?

Thanks for your efforts

**Comment by alexyazvinsky** [comment]
Any update on this?

**Comment by b1zzu** [comment]
@JoaoVFAraujo @dmastag @nationdata-it @davidzxc12 @alexyazvinsky the Aerogear team will be maintaining a fork of the `cordova-plugin-iroot` with all latest bug fixes, you can find the  last version here: https://github.com/aerogear/cordova-plugin-iroot/releases/tag/0.8.1 and the package is also available in npmjs: https://www.npmjs.com/package/@aerogear/cordova-plugin-iroot

**Comment by WuglyakBolgoink** [comment]
@b1zzu @alexyazvinsky @nationdata-it @davidzxc12 @dmastag 

merged and pushed in npm.

I'm so sorry for no response, I'm very ill last half year...

**Comment by WuglyakBolgoink** [comment]
@JoaoVFAraujo @dmastag @nationdata-it @davidzxc12 @alexyazvinsky @b1zzu

I removed in v2.0.0 nodeJS stuff, please check this after release, and feel free to reopen this issue.

tested on `cordova v9.0.0 (cordova-lib@9.0.1)`
