### ISSUE TITLE
'This app is not allowed to query for scheme cydia'

### ISSUE THREAD

**Issue by IllusionVK** [WuglyakBolgoink/cordova-plugin-iroot#22]
Hi, 

Firstly thanks for your time and work on the plugin 👍

When running our app in Xcode we see 2 warnings/errors
`-canOpenURL: failed for URL: "cydia://package/com.example.package" - error: "This app is not allowed to query for scheme cydia"`

`-canOpenURL: failed for URL: "cydia://package/com.fake.package" - error: "This app is not allowed to query for scheme cydia"`

Is this expected behaviour ?  it seems to suggest that the plugin wont be able to do its job, as its being denied access ?  I didn't see any mention of this in previous issues or the documentation.  This [Link](https://github.com/felixgr/secure-ios-app-dev/issues/6) suggests that adding something like this, could give permission ?

```
<key>LSApplicationQueriesSchemes</key>
<array>
 <string>cydia</string>
</array>
```

So, If:
- this is expected, I will add a pull request to update the readme.  
- this is not expected, I guess the readme should instruct users how to give permission ?  

Obviously I have been talking about iOS.  Does Android need anything special?

**Comment by WuglyakBolgoink** [comment]
Hi, I'm not pretty sure, that we should add "cydia" to **LSApplicationQueriesSchemes** for security reason. Do you have maybe an additional information to this problem?

PR'S are always welcome!

**Comment by WuglyakBolgoink** [comment]
> https://github.com/felixgr/secure-ios-app-dev/issues/6

**Comment by WuglyakBolgoink** [comment]
closed.

FYI: https://github.com/WuglyakBolgoink/cordova-plugin-iroot/issues/28
