### ISSUE TITLE
Not able to detect genymotion emulator.

### ISSUE THREAD

**Issue by snj07** [WuglyakBolgoink/cordova-plugin-iroot#24]

**Comment by WuglyakBolgoink** [comment]
@snj07 please create ticket on https://github.com/scottyab/rootbeer, this plugin is mostly only wrapper for this library

**Comment by WuglyakBolgoink** [comment]
@snj07 partial check will be available on v2.0.0

**Comment by WuglyakBolgoink** [comment]
full implementation will be added in v2.1.0

https://github.com/WuglyakBolgoink/cordova-plugin-iroot/issues/30
