### ISSUE TITLE
isRootedRedBeerWithoutBusyBoxCheck is not a function error

### ISSUE THREAD

**Issue by ir2pid** [WuglyakBolgoink/cordova-plugin-iroot#25]
The call isRootedRedBeer is called but when calling isRootedRedBeerWithoutBusyBoxCheck I get the error

IRoot.isRootedRedBeerWithoutBusyBoxCheck is not a function

**Comment by WuglyakBolgoink** [comment]
@ir2pid a new plugin version will be available this week

**Comment by ltin071** [comment]
Sorry is it solved? We hit this problem also. Thanks!

**Comment by WuglyakBolgoink** [comment]
This method is deprecated as checking without the busybox binary is now the *default*. This is because many manufacturers leave this binary on production devices.

https://github.com/scottyab/rootbeer/blob/master/rootbeerlib/src/main/java/com/scottyab/rootbeer/RootBeer.java#L52

**Comment by WuglyakBolgoink** [comment]
fixed
