### ISSUE TITLE
Integrate with meteor

### ISSUE THREAD

**Issue by anhpt86** [WuglyakBolgoink/cordova-plugin-iroot#40]
Hi,

I cannot integrate this plugin with meteor. App will be crashed and loading forever at splash screen.

Does anyone work with meteor.

Thanks.

**Comment by WuglyakBolgoink** [comment]
@anhpt86 can you send me a simple project to reproduce your problem?

**Comment by anhpt86** [comment]
> @anhpt86 can you send me a simple project to reproduce your problem?

Thank you but sorry I cannot send you the source code.

I installed plug by this command line: meteor add cordova:cordova-plugin-iroot
And It's added into my project.
And then I added below code on app start event but app is crashed.

IRoot.isRooted((booleanVal) => {
              console.log('IRoot.isRooted success: ', booleanVal);
            }, (err) => {
              console.log('IRoot.isRooted error:', err);
            });

Do I need to import anything at the beginning of file?

Thank you so muchs.

**Comment by WuglyakBolgoink** [comment]
@anhpt86 which errors you have in logs? and on crash?

**Comment by anhpt86** [comment]
> @anhpt86 which errors you have in logs? and on crash?
> 
> and meteor you mean this -> https://www.meteor.com/ ?

Yes, I'm using that platform.

It's working for me. I'm using older version and it works.

Thank for your support.

**Comment by WuglyakBolgoink** [comment]
@anhpt86 it will begreat to hear what was the problem exactly with "new" version...

**Comment by anhpt86** [comment]
> @anhpt86 it will be great to hear what was the problem exactly with "new" version...

When I run:  **meteor npm view cordova-plugin-iroot versions**

It shows as below image. I used version 2.x but mobile app is crashed at the splash screen and didn't show any error BUT I tried with version 0.8.1 and it's working.

![image](https://user-images.githubusercontent.com/11342936/90503025-f9b5fc80-e178-11ea-9eb6-90c554317fd9.png)

**Comment by WuglyakBolgoink** [comment]
@anhpt86 I need to know what the errors was exactly on your device?!

check Xcode console.log's (iOS) or ADB LogCat logs (Android)

`v2.0.1` work fine on all my devices
