### ISSUE TITLE
 URL: "cydia://package/com.example.package" - error: "The operation couldn’t be completed.  - wkwebview cordova

### ISSUE THREAD

**Issue by BenOron** [WuglyakBolgoink/cordova-plugin-iroot#41]
### When running our with app in Xcode we see warnings/errors

Hello ,

_-canOpenURL: failed for URL: "cydia://package/com.example.package" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

already added: 
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>cydia</string>
	</array>_
 
the app running on cordova with wkwebview 

Thanks Ben

**Comment by WuglyakBolgoink** [comment]
Hallo @BenOron 

> The 10814 errors themselves are expected if the `app` isn't installed, so they're safe to ignore.
