### ISSUE TITLE
New feature: "isRootedRedBeer" with skip option for "BusyBoxBinary"

### ISSUE THREAD

**Issue by SujitSingh** [WuglyakBolgoink/cordova-plugin-iroot#5]
I tried `isRootedRedBeer()` and it started reporting non-rooted device (with `BusyBox` like `MiUI`) as rooted.

Can we add another function which allows us to skip check for `BusyBox` similar what [Rootbeer provides](https://github.com/scottyab/rootbeer/blob/master/README.md) with help of `isRootedWithoutBusyBoxCheck()` along with normal one?

**Comment by WuglyakBolgoink** [comment]
Hallo @sujit77 ,

ok. I will add this function in next release.

**Comment by WuglyakBolgoink** [comment]
@SujitSingh 
added in v0.7.0
