### ISSUE TITLE
Changed min sdk to version 23 and im getting error at compiling

### ISSUE THREAD

**Issue by Alejoprivas** [WuglyakBolgoink/cordova-plugin-iroot#50]
Im adding new plugins to my app, so i changed the minsdk version to 23. Also changed node version to 12.10. Now im getting this error when compiling.

` BUILD FAILED in 4s
Error: /home/alejop/peru/banco.homebanking.frontend/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
.../platforms/android/app/src/main/java/de/cyberkatze/iroot/IRoot.java:223: error: cannot find symbol
                WhatisRooted = rootBeer.checkForRootNative();
                                       ^
  symbol:   method checkForRootNative()
  location: variable rootBeer of type RootBeer
.../app/platforms/android/app/src/main/java/de/cyberkatze/iroot/IRoot.java:334: error: cannot find symbol
            boolean checkRootBeer = rootBeer.isRootedWithBusyBoxCheck();
                                            ^
  symbol:   method isRootedWithBusyBoxCheck()
  location: variable rootBeer of type RootBeer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by WuglyakBolgoink** [comment]
hallo @Alejoprivas can you try top remove platform and reinstall again? do u have the same problem?

**Comment by Alejoprivas** [comment]
i deleted the platforms and plugin folders. let me use the ionic platform remove command and ill be right back at you.+

**Comment by WuglyakBolgoink** [comment]
@Alejoprivas ok

**Comment by Alejoprivas** [comment]
-i ran ionic cordova rm platform android --save
-installed plugin again via ionic cordova plugin iroot.
-ran ionic cordova add platform android --save
-compiled and still have the same issue 

@WuglyakBolgoink

**Comment by WuglyakBolgoink** [comment]
@Alejoprivas can u provide a simple project to reproduce this problem?

**Comment by Alejoprivas** [comment]
ok.

**Comment by Alejoprivas** [comment]
sorry cant recreate the error :/

**Comment by WuglyakBolgoink** [comment]
@Alejoprivas no problem , try to remove all plugins and platforms and install again, maybe something was wrong with dependencies

**Comment by WuglyakBolgoink** [comment]
Closing out, if this is still an issue feel free to reopen.
