### ISSUE TITLE
IRoot version requirement (Ionic app)

### ISSUE THREAD

**Issue by ThePa1nMaZ3** [WuglyakBolgoink/cordova-plugin-iroot#56]
First of all, I thank the author for developing plugin.
I would like to understand why this happens to our project.
My 'cordova prepare' step (I have an Ionic app) fails for this check:

Installing "cordova-plugin-iroot" for browser
Plugin doesn't support this project's cordova version. cordova: 9.0.1, failed version requirement:> = 10.0.0

That's my situation:

cordova -v - --- > 9.0.0 (cordova-lib@9.0.1)

Installed platforms:
  android 10.1.1
  browser 6.0.0
  ios 5.1.1

Should i mean to improve 'global' cordova version? 
Or there is an error in generated package_lock.json (consequently in declarations of min version of of plugin)? 
[package_lock report :       

"engines": {
  "cordova": ">=10.0.0"
}
]
I was expecting a version>= 10 required for android platform only.
Thanks

**Comment by WuglyakBolgoink** [comment]
Hallo @ThePa1nMaZ3 !

`IRoot` support only `cordova v10+`

And you must migrate your setup to 
- cordova@11.0.0
- ios@6.2.0
- android@10.1.1


you must migrate cordova-ios and cordova-android because there are breaking changes after migration to v10 cordova!
