### ISSUE TITLE
NPM repo includes .git folder making it hard to work with.

### ISSUE THREAD

**Issue by pure-zero** [WuglyakBolgoink/cordova-plugin-iroot#6]
Hi I am not to sure about your publishing process, but whenm doing an npm install the repo downloaded includes a .git folder. So we will have issues playing with the repo when using npm and cordova commands. I suggest a entry needs added to the .gitignore as .git/ but there are other ways to do this, as seen here https://docs.npmjs.com/cli/publish

Cheers.

**Comment by WuglyakBolgoink** [comment]
@pure-zero please check with new v0.7.0. `npm publish` was without errors.

**Comment by SujitSingh** [comment]
@WuglyakBolgoink works perfectly for me.
