### ISSUE TITLE
iRoot is not defined, 2nd time launch the app

### ISSUE THREAD

**Issue by Piraban** [WuglyakBolgoink/cordova-plugin-iroot#7]
I have done as a blow

  ````
declare var IRoot: any;

 ngOnInit() {
     if (typeof (IRoot) !== 'undefined' && IRoot) {
         IRoot.isRooted((data) => {
             if (data && data == 1) {
                this.isRootedORJailBreak = true
                console.log("*******This is routed device");
           } else {
               this.isRootedORJailBreak = false
              console.log("*******This is not routed device");
          }
      }, (data) => {
              this.isRootedORJailBreak = false
             console.log("*******routed device detection failed case", data);
      });
 } }
````

The first time launch app, this is working, after that remove the app from a session, then launch the app, it says '**iRoot is not defined**'

Please any help/solution. I am struggling to find a solution more than 3 days.

**Comment by WuglyakBolgoink** [comment]
Hallo @Piraban 

I check this asap. Thanks for report.

**Comment by Piraban** [comment]
Seems this is an issue in this plugin. May I know this can be resolved asap?

**Comment by WuglyakBolgoink** [comment]
@Piraban I'm busy now. But today I try to send fix.

**Comment by WuglyakBolgoink** [comment]
@Piraban are u use ionic? or something else?

**Comment by Piraban** [comment]
Thanks a lot for the quick fix. I am using ionic 3. I will check and update you

**Comment by SujitSingh** [comment]
@Piraban which version of this plugin are you using? Look at [way of implementation in Ionic](https://github.com/WuglyakBolgoink/cordova-plugin-iroot/issues/1/#issuecomment-369512201).

**Comment by WuglyakBolgoink** [comment]
@Piraban any news?

**Comment by ahmednabil88** [comment]
a simple note
Instead of using following check:
`if (data && data === 1)`

We should use the following check:
`if (data && data === true) `

**Comment by bhargavas12** [comment]
@Piraban Is this issue resolved?
I am still getting undefined value for iRoot.

**Comment by WuglyakBolgoink** [comment]
@bhargavas12 this was already fixed. What do you do exactly?
