### ISSUE TITLE
android build issue when the plugin is included

### ISSUE THREAD

**Issue by shaamcom83** [WuglyakBolgoink/cordova-plugin-iroot#9]
Hi, 
I included the cordova-plugin-iroot plugin to the cordova app and getting the below error:
BUILD FAILED in 1m 58s
(node:8816) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
error: failed linking references.

My env is as follows:
Node version: v8.11.3
Cordova version: 8.0.0
cordova-plugin-iroot : 0.7.0

When I remove the iroot plugin and run the project, it is building the apk without any issues.

**Comment by WuglyakBolgoink** [comment]
Hallo @shaamcom83 ,

can you do a simple demo project to reproduce this error? Because this plugin doesn't change any style files.

thank you!

**Comment by shaamcom83** [comment]
Hi @WuglyakBolgoink,
It turns out to be one of the plugin in the project is setting the android sdk version to 23 and that causes the error. 

ext.cdvCompileSdkVersion = 23;

When set it version higher than 23 (in my case 25), it build and the iroot plugin works properly

Thank you-
